
------------------------ TABLE CREATION FOR PROJECT 1387 -- BMI -------------- 21/02/2023 -----------------------------------------------------------------------------------

------------------------------------------------------------------------------ Code Preperation -----------------------------------------------------------------------------

-------------------------------------------------------------- COPD ----------------------------------------------------------------------------------------------

-- Extract all BMI Events 
DECLARE GLOBAL TEMPORARY TABLE BMI_COPD AS (
SELECT id.ALF_PE, wlgp.EVENT_VAL, wlgp.EVENT_DT, wlgp.EVENT_CD, TERM FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wlgp
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_COPD id ON id.ALF_PE = wlgp.ALF_PE 
INNER JOIN sailw1387v.SS_BMI_CODES dtc ON dtc.READCODE = wlgp.EVENT_CD 
WHERE wlgp.EVENT_VAL > 0
AND (wlgp.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND (wlgp.EVENT_CD LIKE '22K%'
AND wlgp.EVENT_CD != '22K9.') 
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Remove errant or misrecorded values
DELETE FROM SESSION.BMI_COPD
WHERE EVENT_VAL NOT BETWEEN 10 AND 100 OR EVENT_DT NOT BETWEEN  '31/12/2014' AND '31/12/2019'

-- Calculate the mean across the cohort 
DECLARE GLOBAL TEMPORARY TABLE MEAN_BMI_COPD AS (
SELECT ALF_PE, SUM(EVENT_VAL)/COUNT(ALF_PE) AS MEAN_BMI
FROM SESSION.BMI_COPD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Select the latest date for each ALF
DECLARE GLOBAL TEMPORARY TABLE LATEST_DATE_BMI_COPD AS (
SELECT ALF_PE, MAX(EVENT_DT) AS latest_event
FROM SESSION.BMI_COPD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Select the latest BMI for each ALF
DECLARE GLOBAL TEMPORARY TABLE LATEST_BMI_COPD AS (
SELECT DISTINCT bc.ALF_PE, latest_event, bc.EVENT_VAL
FROM SESSION.BMI_COPD bc
INNER JOIN SESSION.LATEST_DATE_BMI_COPD ldbc ON ldbc.ALF_PE = bc.ALF_PE AND ldbc.latest_event = bc.EVENT_DT
WHERE ldbc.latest_event = bc.EVENT_DT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.LATEST_BMI_COPD
ORDER BY ALF_PE

SELECT COUNT(ALF_PE) FROM SESSION.LATEST_BMI_COPD

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_BMI_COPD


--------- add in height and weight 

--- establish height for cohort 
DECLARE GLOBAL TEMPORARY TABLE HEIGHT_COPD AS (
SELECT DISTINCT SSA.ALF_PE, wgec.GNDR_CD, ssc.READCODE, wgec.EVENT_VAL, wgec.EVENT_DT 
FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wgec 
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN sailw1387v.SS_BMI_CODES ssc ON ssc.READCODE = wgec.EVENT_CD 
WHERE CATEGORY = 'height'
AND (wgec.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND (wgec.GNDR_CD = '1' OR wgec.GNDR_CD = '2')
AND (wgec.EVENT_VAL BETWEEN '90' AND '200' OR wgec.EVENT_VAL BETWEEN '0.01' AND '2')
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- SELECT MAX DATE PER ALF AND LATEST DATE
DECLARE GLOBAL TEMPORARY TABLE HEIGHT_COPD_MAX AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_VAL) AS LATEST_EVENT
FROM SESSION.HEIGHT_COPD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE HEIGHT_COPD_V2 AS (
SELECT DISTINCT hc.ALF_PE, GNDR_CD, READCODE, EVENT_VAL, EVENT_DT
FROM SESSION.HEIGHT_COPD hc
INNER JOIN SESSION.HEIGHT_COPD_MAX hcm ON hcm.ALF_PE = hc.ALF_PE AND hc.Event_VAL = hcm.LATEST_EVENT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

--- Where duplicates, select greatest value 
DECLARE GLOBAL TEMPORARY TABLE HEIGHT_COPD_LATEST AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_DT) AS LATEST_DATE
FROM SESSION.HEIGHT_COPD_V2
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE HEIGHT_COPD_DISTINCT AS (
SELECT hc.* FROM SESSION.HEIGHT_COPD_V2 hc
INNER JOIN SESSION.HEIGHT_COPD_LATEST hdm ON hdm.ALF_PE = hc.ALF_PE AND hc.Event_DT = hdm.LATEST_DATE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT COUNT(ALF_PE) FROM SESSION.HEIGHT_COPD_DISTINCT

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.HEIGHT_COPD_DISTINCT

SELECT * FROM SESSION.HEIGHT_COPD_DISTINCT
ORDER BY ALF_PE

UPDATE SESSION.HEIGHT_COPD_DISTINCT SET EVENT_VAL = EVENT_VAL/100
WHERE EVENT_VAL > 90 

SELECT * FROM SESSION.HEIGHT_COPD_DISTINCT

--- establish weight for cohort 
DECLARE GLOBAL TEMPORARY TABLE WEIGHT_COPD AS (
SELECT DISTINCT SSA.ALF_PE, wgec.GNDR_CD, ssc.READCODE, wgec.EVENT_VAL, wgec.EVENT_DT 
FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wgec 
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_COPD SSA ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN sailw1387v.SS_BMI_CODES ssc ON ssc.READCODE = wgec.EVENT_CD 
WHERE CATEGORY = 'weight'
AND (wgec.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND (wgec.GNDR_CD = '1' OR wgec.GNDR_CD = '2')
AND (wgec.EVENT_VAL BETWEEN '10' AND '130')
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- SELECT MAX DATE PER ALF AND LATEST DATE
DECLARE GLOBAL TEMPORARY TABLE WEIGHT_COPD_MAX AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_VAL) AS LATEST_EVENT
FROM SESSION.WEIGHT_COPD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE WEIGHT_COPD_V2 AS (
SELECT DISTINCT hc.ALF_PE, GNDR_CD, READCODE, EVENT_VAL, EVENT_DT
FROM SESSION.WEIGHT_COPD hc
INNER JOIN SESSION.WEIGHT_COPD_MAX hcm ON hcm.ALF_PE = hc.ALF_PE AND hc.Event_VAL = hcm.LATEST_EVENT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

--- Where duplicates, select greatest value 
DECLARE GLOBAL TEMPORARY TABLE WEIGHT_COPD_LATEST AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_DT) AS LATEST_DATE
FROM SESSION.WEIGHT_COPD_V2
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE WEIGHT_COPD_DISTINCT AS (
SELECT hc.* FROM SESSION.WEIGHT_COPD_V2 hc
INNER JOIN SESSION.WEIGHT_COPD_LATEST hdm ON hdm.ALF_PE = hc.ALF_PE AND hc.Event_DT = hdm.LATEST_DATE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT COUNT(ALF_PE) FROM SESSION.WEIGHT_COPD_DISTINCT

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.WEIGHT_COPD_DISTINCT

SELECT * FROM SESSION.WEIGHT_COPD_DISTINCT
ORDER BY ALF_PE

--- CALCULATE BMI

DECLARE GLOBAL TEMPORARY TABLE COPD_PREDICTED_BMI AS (
SELECT dti.ALF_PE, SUM(wid.EVENT_VAL/hid.EVENT_VAL) AS CALCULATED_BMI
FROM sailw1387v.SS_DEMOGRAPHIC_TABLE_COPD dti  
INNER JOIN SESSION.HEIGHT_COPD_DISTINCT hid ON hid.ALF_PE = dti.ALF_PE 
INNER JOIN SESSION.WEIGHT_COPD_DISTINCT wid ON wid.ALF_PE = dti.ALF_PE 
GROUP BY dti.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.COPD_PREDICTED_BMI 

---- ADDIN PRE-CALCULATED BMI

DECLARE GLOBAL TEMPORARY TABLE COPD_PREDICTED_BMI_COMBINED AS (
SELECT DISTINCT dtc.ALF_PE,
CASE WHEN fvc.EVENT_VAL IS NULL OR fvc.EVENT_VAL < 7 THEN fbc.CALCULATED_BMI ELSE fvc.EVENT_VAL END AS BMI
FROM sailw1387v.SS_DEMOGRAPHIC_TABLE_COPD dtc
LEFT JOIN SESSION.COPD_PREDICTED_BMI fbc ON fbc.ALF_PE = dtc.ALF_PE
LEFT JOIN SESSION.LATEST_BMI_COPD fvc ON  fvc.ALF_PE = dtc.ALF_PE
WHERE FOLLOW_UP_END > '31/12/2019' AND (DOD > '31/12/2019' OR DOD IS NULL )
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.COPD_PREDICTED_BMI_COMBINED
ORDER BY ALF_PE


---- COUNTS FOR TABLES
DECLARE GLOBAL TEMPORARY TABLE COPD_BMI_COUNT AS (
SELECT COUNT(DISTINCT ALF_PE) AS Counts, BMI FROM SESSION.COPD_PREDICTED_BMI_COMBINED 
GROUP BY BMI
ORDER BY BMI
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT SUM(COUNTS) FROM SESSION.COPD_BMI_COUNT
WHERE BMI < '18.5'AND BMI IS NOT NULL

SELECT SUM(COUNTS) FROM SESSION.COPD_BMI_COUNT
WHERE BMI BETWEEN '18.5'AND '24.9'

SELECT SUM(COUNTS) FROM SESSION.COPD_BMI_COUNT
WHERE BMI BETWEEN  '25' AND '29.9'

SELECT SUM(COUNTS) FROM SESSION.COPD_BMI_COUNT
WHERE BMI > '30'

SELECT SUM(COUNTS) FROM SESSION.COPD_BMI_COUNT
WHERE BMI IS NULL


-------------------------------------------------------------- ILD ----------------------------------------------------------------------------------------------
-- Select All BMI Events for Cohort
DECLARE GLOBAL TEMPORARY TABLE BMI_ILD AS (
SELECT id.ALF_PE, wlgp.EVENT_VAL, wlgp.EVENT_DT, wlgp.EVENT_CD, TERM FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wlgp
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_ILD id ON id.ALF_PE = wlgp.ALF_PE 
INNER JOIN sailw1387v.SS_BMI_CODES dtc ON dtc.READCODE = wlgp.EVENT_CD 
WHERE wlgp.EVENT_VAL > 0
AND (wlgp.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND (wlgp.EVENT_CD LIKE '22K%'
AND wlgp.EVENT_CD != '22K9.') 
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Delete errant or Misrecorded values 
DELETE FROM SESSION.BMI_ILD
WHERE EVENT_VAL NOT BETWEEN 10 AND 100 OR EVENT_DT NOT BETWEEN  '31/12/2014' AND '31/12/2019'

-- Select the Mean BMI for cohort 
DECLARE GLOBAL TEMPORARY TABLE MEAN_BMI_ILD AS (
SELECT ALF_PE, SUM(EVENT_VAL)/COUNT(ALF_PE) AS MEAN_BMI
FROM SESSION.BMI_ILD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.MEAN_BMI_ILD

-- Select the Latest Date for each ALF
DECLARE GLOBAL TEMPORARY TABLE LATEST_DATE_BMI_ILD AS (
SELECT ALF_PE, MAX(EVENT_DT) AS latest_event
FROM SESSION.BMI_ILD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- Select the latest BMI for each ALF
DECLARE GLOBAL TEMPORARY TABLE LATEST_BMI_ILD AS (
SELECT DISTINCT bc.ALF_PE, latest_event, bc.EVENT_VAL
FROM SESSION.BMI_ILD bc
INNER JOIN SESSION.LATEST_DATE_BMI_ILD ldbc ON ldbc.ALF_PE = bc.ALF_PE AND ldbc.latest_event = bc.EVENT_DT
WHERE ldbc.latest_event = bc.EVENT_DT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.LATEST_BMI_ILD
ORDER BY ALF_PE

SELECT COUNT(ALF_PE) FROM SESSION.LATEST_BMI_ILD

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_BMI_ILD

--------- add in height and weight 
--- establish height for cohort 
DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ILD AS (
SELECT DISTINCT SSA.ALF_PE, wgec.GNDR_CD, ssc.READCODE, wgec.EVENT_VAL, wgec.EVENT_DT 
FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wgec 
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_ILD SSA ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN sailw1387v.SS_BMI_CODES ssc ON ssc.READCODE = wgec.EVENT_CD 
WHERE CATEGORY = 'height'
AND (wgec.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND (wgec.GNDR_CD = '1' OR wgec.GNDR_CD = '2')
AND (wgec.EVENT_VAL BETWEEN '90' AND '200' OR wgec.EVENT_VAL BETWEEN '0.01' AND '2')
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- SELECT MAX DATE PER ALF AND LATEST DATE
DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ILD_MAX AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_VAL) AS LATEST_EVENT
FROM SESSION.HEIGHT_ILD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ILD_V2 AS (
SELECT DISTINCT hc.ALF_PE, GNDR_CD, READCODE, EVENT_VAL, EVENT_DT
FROM SESSION.HEIGHT_ILD hc
INNER JOIN SESSION.HEIGHT_ILD_MAX hcm ON hcm.ALF_PE = hc.ALF_PE AND hc.Event_VAL = hcm.LATEST_EVENT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

--- Where duplicates, select greatest value 
DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ILD_LATEST AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_DT) AS LATEST_DATE
FROM SESSION.HEIGHT_ILD_V2
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ILD_DISTINCT AS (
SELECT hc.* FROM SESSION.HEIGHT_ILD_V2 hc
INNER JOIN SESSION.HEIGHT_ILD_LATEST hdm ON hdm.ALF_PE = hc.ALF_PE AND hc.Event_DT = hdm.LATEST_DATE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT COUNT(ALF_PE) FROM SESSION.HEIGHT_ILD_DISTINCT

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.HEIGHT_ILD_DISTINCT

SELECT * FROM SESSION.HEIGHT_ILD_DISTINCT
ORDER BY ALF_PE

UPDATE SESSION.HEIGHT_ILD_DISTINCT SET EVENT_VAL = EVENT_VAL/100
WHERE EVENT_VAL > 90 

SELECT * FROM SESSION.HEIGHT_ILD_DISTINCT

--- establish weight for cohort 
DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ILD AS (
SELECT DISTINCT SSA.ALF_PE, wgec.GNDR_CD, ssc.READCODE, wgec.EVENT_VAL, wgec.EVENT_DT 
FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wgec 
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_ILD SSA ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN sailw1387v.SS_BMI_CODES ssc ON ssc.READCODE = wgec.EVENT_CD 
WHERE CATEGORY = 'weight'
AND (wgec.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND (wgec.GNDR_CD = '1' OR wgec.GNDR_CD = '2')
AND (wgec.EVENT_VAL BETWEEN '10' AND '130')
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- SELECT MAX DATE PER ALF AND LATEST DATE
DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ILD_MAX AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_VAL) AS LATEST_EVENT
FROM SESSION.WEIGHT_ILD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ILD_V2 AS (
SELECT DISTINCT hc.ALF_PE, GNDR_CD, READCODE, EVENT_VAL, EVENT_DT
FROM SESSION.WEIGHT_ILD hc
INNER JOIN SESSION.WEIGHT_ILD_MAX hcm ON hcm.ALF_PE = hc.ALF_PE AND hc.Event_VAL = hcm.LATEST_EVENT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

--- Where duplicates, select greatest value 
DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ILD_LATEST AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_DT) AS LATEST_DATE
FROM SESSION.WEIGHT_ILD_V2
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ILD_DISTINCT AS (
SELECT hc.* FROM SESSION.WEIGHT_ILD_V2 hc
INNER JOIN SESSION.WEIGHT_ILD_LATEST hdm ON hdm.ALF_PE = hc.ALF_PE AND hc.Event_DT = hdm.LATEST_DATE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;


--- CALCULATE BMI

DECLARE GLOBAL TEMPORARY TABLE ILD_PREDICTED_BMI AS (
SELECT dti.ALF_PE, SUM(wid.EVENT_VAL/hid.EVENT_VAL) AS CALCULATED_BMI
FROM sailw1387v.SS_DEMOGRAPHIC_TABLE_ILD dti  
INNER JOIN SESSION.HEIGHT_ILD_DISTINCT hid ON hid.ALF_PE = dti.ALF_PE 
INNER JOIN SESSION.WEIGHT_ILD_DISTINCT wid ON wid.ALF_PE = dti.ALF_PE 
GROUP BY dti.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

---- ADDIN PRE-CALCULATED BMI

DECLARE GLOBAL TEMPORARY TABLE ILD_PREDICTED_BMI_COMBINED AS (
SELECT dtc.ALF_PE,
CASE WHEN fvc.EVENT_VAL IS NULL OR fvc.EVENT_VAL < 7 THEN fbc.CALCULATED_BMI ELSE fvc.EVENT_VAL END AS BMI
FROM sailw1387v.SS_DEMOGRAPHIC_TABLE_ILD dtc
LEFT JOIN SESSION.ILD_PREDICTED_BMI fbc ON fbc.ALF_PE = dtc.ALF_PE
LEFT JOIN SESSION.LATEST_BMI_ILD fvc ON  fvc.ALF_PE = dtc.ALF_PE
WHERE FOLLOW_UP_END > '31/12/2019' AND (DOD > '31/12/2019' OR DOD IS NULL )
) WITH DATA WITH replace ON commit PRESERVE ROWS ;


---- COUNTS FOR TABLES
DECLARE GLOBAL TEMPORARY TABLE ILD_BMI_COUNT AS (
SELECT COUNT(DISTINCT ALF_PE) AS Counts, BMI FROM SESSION.ILD_PREDICTED_BMI_COMBINED 
GROUP BY BMI
ORDER BY BMI
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT SUM(COUNTS) FROM SESSION.ILD_BMI_COUNT
WHERE BMI < '18.5'

SELECT SUM(COUNTS) FROM SESSION.ILD_BMI_COUNT
WHERE BMI BETWEEN '18.5'AND '24.9'

SELECT SUM(COUNTS) FROM SESSION.ILD_BMI_COUNT
WHERE BMI BETWEEN  '25' AND '29.9'

SELECT SUM(COUNTS) FROM SESSION.ILD_BMI_COUNT
WHERE BMI > '30'

SELECT SUM(COUNTS) FROM SESSION.ILD_BMI_COUNT
WHERE BMI IS NULL

-------------------------------------------------------------- ASTHMA ----------------------------------------------------------------------------------------------
DECLARE GLOBAL TEMPORARY TABLE BMI_ASTHMA AS (
SELECT id.ALF_PE, wlgp.EVENT_VAL, wlgp.EVENT_DT, wlgp.EVENT_CD, TERM FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wlgp
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_ASTHMA id ON id.ALF_PE = wlgp.ALF_PE 
INNER JOIN sailw1387v.SS_BMI_CODES dtc ON dtc.READCODE = wlgp.EVENT_CD 
WHERE wlgp.EVENT_VAL > 0
AND (wlgp.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND (wlgp.EVENT_CD LIKE '22K%'
AND wlgp.EVENT_CD != '22K9.') 
AND DAYS(wlgp.EVENT_DT) - DAYS(id.WOB) >= 18*365.25
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DELETE FROM SESSION.BMI_ASTHMA
WHERE EVENT_VAL NOT BETWEEN 10 AND 100 OR EVENT_DT NOT BETWEEN  '31/12/2014' AND '31/12/2019'

DECLARE GLOBAL TEMPORARY TABLE MEAN_BMI_ASTHMA AS (
SELECT ALF_PE, SUM(EVENT_VAL)/COUNT(ALF_PE) AS MEAN_BMI
FROM SESSION.BMI_ASTHMA
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.MEAN_BMI_ASTHMA

DECLARE GLOBAL TEMPORARY TABLE LATEST_DATE_BMI_ASTHMA AS (
SELECT ALF_PE, MAX(EVENT_DT) AS latest_event
FROM SESSION.BMI_ASTHMA
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE LATEST_BMI_ASTHMA AS (
SELECT DISTINCT bc.ALF_PE, latest_event, bc.EVENT_VAL
FROM SESSION.BMI_ASTHMA bc
INNER JOIN SESSION.LATEST_DATE_BMI_ASTHMA ldbc ON ldbc.ALF_PE = bc.ALF_PE AND ldbc.latest_event = bc.EVENT_DT
WHERE ldbc.latest_event = bc.EVENT_DT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.LATEST_BMI_ASTHMA
ORDER BY ALF_PE

SELECT COUNT(ALF_PE) FROM SESSION.LATEST_BMI_ASTHMA

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_BMI_ASTHMA

--------- add in height and weight 

--- establish height for cohort 
DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ASTHMA AS (
SELECT DISTINCT SSA.ALF_PE, wgec.GNDR_CD, ssc.READCODE, wgec.EVENT_VAL, wgec.EVENT_DT 
FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wgec 
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_ASTHMA SSA ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN sailw1387v.SS_BMI_CODES ssc ON ssc.READCODE = wgec.EVENT_CD 
WHERE CATEGORY = 'height'
AND (wgec.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND (wgec.GNDR_CD = '1' OR wgec.GNDR_CD = '2')
AND (wgec.EVENT_VAL BETWEEN '90' AND '200' OR wgec.EVENT_VAL BETWEEN '0.01' AND '2')
AND DAYS(wgec.EVENT_DT) - DAYS(SSA.WOB) >= 18*365.25
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- SELECT MAX DATE PER ALF AND LATEST DATE
DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ASTHMA_MAX AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_VAL) AS LATEST_EVENT
FROM SESSION.HEIGHT_ASTHMA
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ASTHMA_V2 AS (
SELECT DISTINCT hc.ALF_PE, GNDR_CD, READCODE, EVENT_VAL, EVENT_DT
FROM SESSION.HEIGHT_ASTHMA hc
INNER JOIN SESSION.HEIGHT_ASTHMA_MAX hcm ON hcm.ALF_PE = hc.ALF_PE AND hc.Event_VAL = hcm.LATEST_EVENT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

--- Where duplicates, select greatest value 
DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ASTHMA_LATEST AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_DT) AS LATEST_DATE
FROM SESSION.HEIGHT_ASTHMA_V2
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE HEIGHT_ASTHMA_DISTINCT AS (
SELECT hc.* FROM SESSION.HEIGHT_ASTHMA_V2 hc
INNER JOIN SESSION.HEIGHT_ASTHMA_LATEST hdm ON hdm.ALF_PE = hc.ALF_PE AND hc.Event_DT = hdm.LATEST_DATE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT COUNT(ALF_PE) FROM SESSION.HEIGHT_ASTHMA_DISTINCT

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.HEIGHT_ASTHMA_DISTINCT

SELECT * FROM SESSION.HEIGHT_ASTHMA_DISTINCT
ORDER BY ALF_PE

UPDATE SESSION.HEIGHT_ASTHMA_DISTINCT SET EVENT_VAL = EVENT_VAL/100
WHERE EVENT_VAL > 90 

SELECT * FROM SESSION.HEIGHT_ASTHMA_DISTINCT

--- establish weight for cohort 
DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ASTHMA AS (
SELECT DISTINCT SSA.ALF_PE, wgec.GNDR_CD, ssc.READCODE, wgec.EVENT_VAL, wgec.EVENT_DT 
FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wgec 
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_ASTHMA SSA ON wgec.ALF_PE = SSA.ALF_PE
INNER JOIN sailw1387v.SS_BMI_CODES ssc ON ssc.READCODE = wgec.EVENT_CD 
WHERE CATEGORY = 'weight'
AND (wgec.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND (wgec.GNDR_CD = '1' OR wgec.GNDR_CD = '2')
AND (wgec.EVENT_VAL BETWEEN '10' AND '130')
AND DAYS(wgec.EVENT_DT) - DAYS(SSA.WOB) >= 18*365.25
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- SELECT MAX DATE PER ALF AND LATEST DATE
DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ASTHMA_MAX AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_VAL) AS LATEST_EVENT
FROM SESSION.WEIGHT_ASTHMA
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ASTHMA_V2 AS (
SELECT DISTINCT hc.ALF_PE, GNDR_CD, READCODE, EVENT_VAL, EVENT_DT
FROM SESSION.WEIGHT_ASTHMA hc
INNER JOIN SESSION.WEIGHT_ASTHMA_MAX hcm ON hcm.ALF_PE = hc.ALF_PE AND hc.Event_VAL = hcm.LATEST_EVENT
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

--- Where duplicates, select greatest value 
DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ASTHMA_LATEST AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_DT) AS LATEST_DATE
FROM SESSION.WEIGHT_ASTHMA_V2
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE WEIGHT_ASTHMA_DISTINCT AS (
SELECT hc.* FROM SESSION.WEIGHT_ASTHMA_V2 hc
INNER JOIN SESSION.WEIGHT_ASTHMA_LATEST hdm ON hdm.ALF_PE = hc.ALF_PE AND hc.Event_DT = hdm.LATEST_DATE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;


--- CALCULATE BMI

DECLARE GLOBAL TEMPORARY TABLE ASTHMA_PREDICTED_BMI AS (
SELECT dti.ALF_PE, SUM(wid.EVENT_VAL/hid.EVENT_VAL) AS CALCULATED_BMI
FROM sailw1387v.SS_DEMOGRAPHIC_TABLE_ASTHMA dti  
INNER JOIN SESSION.HEIGHT_ASTHMA_DISTINCT hid ON hid.ALF_PE = dti.ALF_PE 
INNER JOIN SESSION.WEIGHT_ASTHMA_DISTINCT wid ON wid.ALF_PE = dti.ALF_PE 
GROUP BY dti.ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

---- ADDIN PRE-CALCULATED BMI

DECLARE GLOBAL TEMPORARY TABLE ASTHMA_PREDICTED_BMI_COMBINED AS (
SELECT dtc.ALF_PE,
CASE WHEN fvc.EVENT_VAL IS NULL OR fvc.EVENT_VAL < 7 THEN fbc.CALCULATED_BMI ELSE fvc.EVENT_VAL END AS BMI
FROM sailw1387v.SS_DEMOGRAPHIC_TABLE_ASTHMA dtc
LEFT JOIN SESSION.ASTHMA_PREDICTED_BMI fbc ON fbc.ALF_PE = dtc.ALF_PE
LEFT JOIN SESSION.LATEST_BMI_ASTHMA fvc ON  fvc.ALF_PE = dtc.ALF_PE
WHERE FOLLOW_UP_END > '31/12/2019' AND (DOD > '31/12/2019' OR DOD IS NULL )
) WITH DATA WITH replace ON commit PRESERVE ROWS ;


---- COUNTS FOR TABLES
DECLARE GLOBAL TEMPORARY TABLE ASTHMA_BMI_COUNT AS (
SELECT COUNT(DISTINCT ALF_PE) AS Counts, BMI FROM SESSION.ASTHMA_PREDICTED_BMI_COMBINED 
GROUP BY BMI
ORDER BY BMI
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT SUM(COUNTS) FROM SESSION.ASTHMA_BMI_COUNT
WHERE BMI < '18.5'

SELECT SUM(COUNTS) FROM SESSION.ASTHMA_BMI_COUNT
WHERE BMI BETWEEN '18.5'AND '24.9'

SELECT SUM(COUNTS) FROM SESSION.ASTHMA_BMI_COUNT
WHERE BMI BETWEEN  '25' AND '29.9'

SELECT SUM(COUNTS) FROM SESSION.ASTHMA_BMI_COUNT
WHERE BMI > '30'

SELECT SUM(COUNTS) FROM SESSION.ASTHMA_BMI_COUNT
WHERE BMI IS NULL