------------------------ TABLE CREATION FOR PROJECT 1387 -- Smoking  -------------- 02/03/2023 

-------------------------------------------------------------------------------- Smoking ----------------------------------------------------------------------------------------
-- CREATE GLOBAL SMOKING CODES TABLE

--DROP TABLE TO ADD CHANGES
DROP TABLE sailw1387v.SS_SMOKING_CODES

CREATE TABLE sailw1387v.SS_SMOKING_CODES(
readcode VARCHAR(5)	
,term	VARCHAR(100)
,smoking_status	INT
,ever_smoker INT
)

DELETE FROM sailw1387v.SS_SMOKING_CODES WHERE readcode = 'NA'

------- COPD ---------

DECLARE GLOBAL TEMPORARY TABLE SMOKING_STATUS_ALL_TIME_COPD AS (SELECT DISTINCT wgec.ALF_PE, YEAR(dtc.WOB) AS YEAR_OF_BIRTH, wgec.GNDR_CD, readcode, wgec.EVENT_DT  ,term ,smoking_status ,ever_smoker
FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wgec 
INNER JOIN sailw1387v.SS_SMOKING_CODES sc ON sc.readcode = wgec.EVENT_CD 
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_COPD dtc ON wgec.ALF_PE = dtc.ALF_PE 
WHERE (wgec.GNDR_CD = '1' OR wgec.GNDR_CD = '2')  AND (DOD > '01/01/2004' OR DOD IS NULL)
AND (wgec.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND FOLLOW_UP_END > '31/12/2019' AND (DOD > '31/12/2019' OR DOD IS NULL )
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- FIND NEVER SMOKERS 

DECLARE GLOBAL TEMPORARY TABLE SMOKING_STATUS_COUNT AS (
SELECT DISTINCT ALF_PE, SUM(EVER_SMOKER) AS Counts FROM SESSION.SMOKING_STATUS_ALL_TIME_COPD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE SMOKER_VS_NON_SMOKERS_COPD AS (
SELECT DISTINCT ALF_PE, CASE WHEN COUNTS = '0' THEN 'NEVER-SMOKER' ELSE 'SMOKER' END AS SMOKER 
FROM SESSION.SMOKING_STATUS_COUNT
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.SMOKER_VS_NON_SMOKERS_COPD

SELECT COUNT(DISTINCT ALF_PE), SMOKER 
FROM SESSION.SMOKER_VS_NON_SMOKERS_COPD
GROUP BY SMOKER
ORDER BY SMOKER

-- FIND EX AND CURRENT SMOKERS
DECLARE GLOBAL TEMPORARY TABLE MAX_SMOKING_DATE_COPD AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_DT) AS LATEST_DATE
FROM SESSION.SMOKING_STATUS_ALL_TIME_COPD 
GROUP BY ALF_PE 
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE LATEST_SMOKING_COPD AS (
SELECT DISTINCT ssati.ALF_PE, EVENT_DT, readcode ,term ,smoking_status ,ever_smoker
FROM SESSION.SMOKING_STATUS_ALL_TIME_COPD ssati
INNER JOIN SESSION.MAX_SMOKING_DATE_COPD msd ON msd.alf_pe = ssati.alf_PE AND msd.LATEST_DATE = ssati.event_dt 
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.LATEST_SMOKING_COPD

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_SMOKING_COPD 
WHERE SMOKING_STATUS = '2' 

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_SMOKING_COPD 
WHERE SMOKING_STATUS = '1'

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_SMOKING_COPD 
WHERE SMOKING_STATUS = '0'

SELECT * FROM sailw1387v.SS_SMOKING_CODES

------------------------------------------------------------------------------------ ILD -----------------------------------------------------------------------------------------------------------

DECLARE GLOBAL TEMPORARY TABLE SMOKING_STATUS_ALL_TIME_ILD AS (SELECT DISTINCT wgec.ALF_PE, YEAR(dtc.WOB) AS YEAR_OF_BIRTH, wgec.GNDR_CD, readcode, wgec.EVENT_DT  ,term ,smoking_status ,ever_smoker
FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wgec 
INNER JOIN sailw1387v.SS_SMOKING_CODES sc ON sc.readcode = wgec.EVENT_CD 
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_ILD dtc ON wgec.ALF_PE = dtc.ALF_PE 
WHERE (wgec.GNDR_CD = '1' OR wgec.GNDR_CD = '2')  AND (DOD > '01/01/2004' OR DOD IS NULL)
AND (wgec.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND FOLLOW_UP_END > '31/12/2019' AND (DOD > '31/12/2019' OR DOD IS NULL )
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- FIND NEVER SMOKERS

DECLARE GLOBAL TEMPORARY TABLE SMOKING_STATUS_COUNTS_ILD AS (
SELECT DISTINCT ALF_PE, SUM(EVER_SMOKER) AS Counts FROM SESSION.SMOKING_STATUS_ALL_TIME_ILD
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE SMOKER_VS_NON_SMOKERS_ILD AS (
SELECT DISTINCT ALF_PE, CASE WHEN COUNTS = '0' THEN 'NON-SMOKER' ELSE 'SMOKER' END AS SMOKER 
FROM SESSION.SMOKING_STATUS_COUNTS_ILD
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.SMOKER_VS_NON_SMOKERS_ILD

SELECT COUNT(DISTINCT ALF_PE), SMOKER 
FROM SESSION.SMOKER_VS_NON_SMOKERS_ILD
GROUP BY SMOKER
ORDER BY SMOKER

-- FIND CURRENT AND EX_SMOKERS
DECLARE GLOBAL TEMPORARY TABLE MAX_SMOKING_DATE_ILD AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_DT) AS LATEST_DATE
FROM SESSION.SMOKING_STATUS_ALL_TIME_ILD 
GROUP BY ALF_PE 
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE LATEST_SMOKING_ILD AS (
SELECT DISTINCT ssati.ALF_PE, EVENT_DT, readcode ,term ,smoking_status ,ever_smoker
FROM SESSION.SMOKING_STATUS_ALL_TIME_ILD ssati
INNER JOIN SESSION.MAX_SMOKING_DATE_ILD msd ON msd.alf_pe = ssati.alf_PE AND msd.LATEST_DATE = ssati.event_dt 
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.LATEST_SMOKING_ILD

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_SMOKING_ILD 
WHERE SMOKING_STATUS = '2'

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_SMOKING_ILD 
WHERE SMOKING_STATUS = '1'

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_SMOKING_ILD 
WHERE SMOKING_STATUS = '0'

------------------------------------------------------------------------------------ ASTHMA -----------------------------------------------------------------------------------------------------------

DECLARE GLOBAL TEMPORARY TABLE SMOKING_STATUS_ALL_TIME_ASTHMA AS (SELECT DISTINCT wgec.ALF_PE, YEAR(dtc.WOB) AS YEAR_OF_BIRTH, wgec.GNDR_CD, readcode, wgec.EVENT_DT  ,term ,smoking_status ,ever_smoker
FROM SAIL1387V.WLGP_GP_EVENT_CLEANSED_20220201 wgec 
INNER JOIN sailw1387v.SS_SMOKING_CODES sc ON sc.readcode = wgec.EVENT_CD 
INNER JOIN sailw1387v.SS_DEMOGRAPHIC_TABLE_ASTHMA dtc ON wgec.ALF_PE = dtc.ALF_PE 
WHERE (wgec.GNDR_CD = '1' OR wgec.GNDR_CD = '2')  AND (DOD > '01/01/2004' OR DOD IS NULL)
AND (wgec.EVENT_DT BETWEEN  '31/12/2014' AND '31/12/2019')
AND FOLLOW_UP_END > '31/12/2019' AND (DOD > '31/12/2019' OR DOD IS NULL )
AND DAYS(wgec.EVENT_DT) - DAYS(dtc.WOB) >= 18*365.25
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

-- FIND NEVER SMOKERS

DECLARE GLOBAL TEMPORARY TABLE SMOKING_STATUS_COUNTS_ASTHMA AS (
SELECT DISTINCT ALF_PE, SUM(EVER_SMOKER) AS Counts FROM SESSION.SMOKING_STATUS_ALL_TIME_ASTHMA
GROUP BY ALF_PE
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE SMOKER_VS_NON_SMOKERS_ASTHMA AS (
SELECT DISTINCT ALF_PE, CASE WHEN COUNTS = '0' THEN 'NON-SMOKER' ELSE 'SMOKER' END AS SMOKER 
FROM SESSION.SMOKING_STATUS_COUNTS_ASTHMA
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.SMOKER_VS_NON_SMOKERS_ASTHMA

SELECT COUNT(DISTINCT ALF_PE), SMOKER 
FROM SESSION.SMOKER_VS_NON_SMOKERS_ASTHMA
GROUP BY SMOKER
ORDER BY SMOKER

-- FIND CURRENT AND EX_SMOKERS
DECLARE GLOBAL TEMPORARY TABLE MAX_SMOKING_DATE_ASTHMA AS (
SELECT DISTINCT ALF_PE, MAX(EVENT_DT) AS LATEST_DATE
FROM SESSION.SMOKING_STATUS_ALL_TIME_ASTHMA 
GROUP BY ALF_PE 
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

DECLARE GLOBAL TEMPORARY TABLE LATEST_SMOKING_ASTHMA AS (
SELECT DISTINCT ssati.ALF_PE, EVENT_DT, readcode ,term ,smoking_status ,ever_smoker
FROM SESSION.SMOKING_STATUS_ALL_TIME_ASTHMA ssati
INNER JOIN SESSION.MAX_SMOKING_DATE_ASTHMA msd ON msd.alf_pe = ssati.alf_PE AND msd.LATEST_DATE = ssati.event_dt 
ORDER BY ALF_PE
) WITH DATA WITH replace ON commit PRESERVE ROWS ;

SELECT * FROM SESSION.LATEST_SMOKING_ASTHMA

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_SMOKING_ASTHMA 
WHERE SMOKING_STATUS = '2'

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_SMOKING_ASTHMA 
WHERE SMOKING_STATUS = '1'

SELECT COUNT(DISTINCT ALF_PE) FROM SESSION.LATEST_SMOKING_ASTHMA 
WHERE SMOKING_STATUS = '0'

